In [1]:
import pandas as pd
import numpy as np
import os

In [ ]:
def convertMonth(x):
       return {
        '08': 'Aug',
        '07': 'July',
        '06': 'June'
    }.get(x,None)

In [2]:
#Get Active Batter List
ActiveBatterList = pd.read_csv("./DataBaseCrawler/MLBBatterRoster2018.csv",index_col=0)
ActivePitcherList = pd.read_csv("./DataBaseCrawler/MLBBatterRoster2018.csv",index_col=0)

In [3]:
ActiveBatterList.head()

,Name,Team,ID,Link,G,AB,PA,H,1B,2B,...,BB,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG
0,J.D. Martinez,Red Sox,6184,statsd.aspx?playerid=6184&position=OF&type=1&g...,122,466,529,155,82,34,...,55,7,123,4,4,0,15,5,1,0.333
1,Andrew Benintendi,Red Sox,17901,statsd.aspx?playerid=17901&position=OF&type=1&...,121,468,539,139,83,35,...,63,1,87,2,6,0,6,20,2,0.297
2,Brock Holt,Red Sox,9345,statsd.aspx?playerid=9345&position=2B/OF&type=...,85,264,300,70,51,15,...,29,2,52,5,2,0,6,6,6,0.265
3,Eduardo Nunez,Red Sox,6848,statsd.aspx?playerid=6848&position=3B/SS&type=...,107,408,426,105,75,20,...,13,0,63,2,2,1,16,7,2,0.257
4,Ian Kinsler,Red Sox,6195,statsd.aspx?playerid=6195&position=2B&type=1&g...,9,28,31,7,6,1,...,3,0,6,0,0,0,0,2,2,0.250

In [4]:
ID = 6184
GameLog = pd.read_csv("./DataBaseCrawler/GameLogs/Batters/"+str(ID)+"GL.csv",index_col=0)

In [5]:
FPHistory = GameLog[['Date', 'Team', 'Opp', 'DKfp']]
x = ['2018' in x for x in FPHistory['Date'].values]
Results2018=FPHistory[x]

In [6]:
#Convert Dates

           Date Team   Opp  DKfp
1    2018-08-23  BOS   CLE  11.0
2    2018-08-21  BOS   CLE   5.0
3    2018-08-19  BOS   TBR   0.0
4    2018-08-17  BOS   TBR  11.0
5    2018-08-14  BOS  @PHI   3.0
6    2018-08-11  BOS  @BAL  34.0
7    2018-08-10  BOS  @BAL  18.0
8    2018-08-08  BOS  @TOR  17.0
9    2018-08-05  BOS   NYY   9.0
10   2018-08-03  BOS   NYY   7.0
11   2018-08-02  BOS   NYY  26.0
12   2018-07-30  BOS   PHI   2.0
13   2018-07-28  BOS   MIN  21.0
14   2018-07-26  BOS   MIN   3.0
15   2018-07-23  BOS  @BAL  10.0
16   2018-07-20  BOS  @DET   2.0
17   2018-07-14  BOS   TOR  18.0
18   2018-07-12  BOS   TOR   3.0
19   2018-07-10  BOS   TEX   7.0
20   2018-07-07  BOS  @KCR  14.0
21   2018-07-06  BOS  @KCR  21.0
22   2018-07-03  BOS  @WSN  25.0
23   2018-06-30  BOS  @NYY  17.0
24   2018-06-28  BOS   LAA   4.0
25   2018-06-26  BOS   LAA  19.0
26   2018-06-23  BOS   SEA   8.0
27   2018-06-21  BOS  @MIN  14.0
28   2018-06-19  BOS  @MIN   6.0
29   2018-06-16  BOS  @SEA   0.0
30   2018-06-14  BOS  @SEA   8.0
..          ...  ...   ...   ...
499  2018-06-10  BOS   CHW   9.0
500  2018-06-07  BOS   DET   2.0
501  2018-06-05  BOS   DET  23.0
502  2018-06-02  BOS  @HOU  15.0
503  2018-05-31  BOS  @HOU   2.0
504  2018-05-29  BOS   TOR  12.0
505  2018-05-26  BOS   ATL   2.0
506  2018-05-24  BOS  @TBR   0.0
507  2018-05-20  BOS   BAL  32.0
508  2018-05-18  BOS   BAL  10.0
509  2018-05-16  BOS   OAK  20.0
510  2018-05-14  BOS   OAK  17.0
511  2018-05-12  BOS  @TOR   2.0
512  2018-05-10  BOS  @NYY  16.0
513  2018-05-08  BOS  @NYY   5.0
514  2018-05-05  BOS  @TEX  10.0
515  2018-05-03  BOS  @TEX   6.0
516  2018-04-30  BOS   KCR  14.0
517  2018-04-28  BOS   TBR   2.0
518  2018-04-26  BOS  @TOR  21.0
519  2018-04-24  BOS  @TOR   0.0
520  2018-04-21  BOS  @OAK   0.0
521  2018-04-18  BOS  @LAA  27.0
522  2018-04-15  BOS   BAL   4.0
523  2018-04-13  BOS   BAL  10.0
524  2018-04-11  BOS   NYY  23.0
525  2018-04-07  BOS   TBR  20.0
526  2018-04-03  BOS  @MIA   5.0
527  2018-03-31  BOS  @TBR  10.0
528  2018-03-29  BOS  @TBR   4.0

[122 rows x 4 columns]